# Basic
markdown: kramdown
title: Dark`Kris
subtitle: Private blog
description: I'm spark , hope you fire
# 头像里面的标题
avatarTitle: 王熠弘
# 头像里面的描述
avatarDesc: Reign in Hell
url: "http://darkkris.github.io"

# Comment
comment:
    # disqus: DarkKris
    # duoshuo: DarkKris
    # cloudTie: DarkKris

# Social
social:
    weibo: DarkKris 
    github: DarkKris
    twitter: long4664030
    mail: long4664030@163.com
    gplus: 105038708474545427650

# 百度统计 
# 使用博客模板请去掉或者更换 id 
# baidu:
#     id:94bd6d5efd92345bf72bd9c19bd16f49

# Google Analytics
# 使用博客模板请去掉或者更换 id
# ga:
#     id: UA-102043025-1   
#     host: auto  


# 《----------------- 上面的信息修改成你自己的 ---------------------------》
#
#
#  _post/ 下的文章更换成你自己的文章
#  帮忙star一下，感谢~😆 地址： https://github.com/leopardpan/leopardpan.github.io
#
#
# 《--------------- 下面的信息可以自行选择是否修改 ------------------------》


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: Home

# Navigation buttons in the front page.s
nav:
    - {title: Articles, description: archive, url: '/archive'}   
    - {title: Tags, description: tags, url: '/tags'}      
    - {title: About, description: about, url: '/about'}      
    

# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"


